# Setup
title:               Methods in Spatial Research 
tagline:             ''
description:         'Methods in Spatial Research is a course offered at Columbia GSAPP by the <a target='blank' href="https://c4sr.columbia.edu">Center for Spatial Research</a>. Spring 2021.'
url:                 https://darebrawley.github.io
baseurl:             '/course-template'
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Dare Brawley
  url:               https://darebrawley.net
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
